### ISSUE TITLE
Propose updating to Mattermost 3.5.1

### ISSUE THREAD

**Issue by jasonblais** [goern/mattermost-openshift#11]
Hey @goern, 

Just wanted to inform you that Mattermost 3.5.1 release has been cut.

The new release contains security updates and several API changes - you can [view the full changelog for Mattermost 3.5.1 here](https://docs.mattermost.com/administration/changelog.html#release-v3-5-1) and [find download links with hash numbers here](https://pre-release.mattermost.com/core/pl/m43r4fnr4fgrfy1gq61rpjregc)

Wondering if you'd like to help update the OpenShift Installer to be compatible with Mattermost 3.5?

If you do update, please consider tweeting about it, which we can then retweet for greater reach.

Also, feel free to join the [Mattermost Installers community channel](https://pre-release.mattermost.com/core/channels/installers-and-images) for latest news relevant for installer owners.

**Comment by goern** [comment]
@syamgk @jfchevrette do you want to have a look at it, otherwise I will do it next week...

**Comment by goern** [comment]
closed by 80baf02db5653a0853de608585d2fee97b2e6d4d
