### ISSUE TITLE
error: build error: non-zero (13) exit code from goern/go-16-centos7

### ISSUE THREAD

**Issue by carlpett** [goern/mattermost-openshift#15]
I'm trying to run this in our OpenShift, but getting this error on build:

    error: build error: non-zero (13) exit code from goern/go-16-centos7@sha256:6479f56324c76685c46d352c81e36ea27a2127d4571d3190b474b4932feb4372

There are a few 404:s in the log ([gist here](https://gist.github.com/carlpett/5bf45ea124430e54078444a7420b1b92)). Maybe they require Go 1.7 to build? 

I tried a few older tags instead of master, but same results

**Comment by goern** [comment]
hi there, thanks for the report. I was able to reproduce the problem and will have a look at it... pls hang on ;)

**Comment by carlpett** [comment]
Hanging on as best as I can :) Anything I can do to help?

**Comment by goern** [comment]
So, free time slots are rare. But the workaround for the moment seem to be to use the Docker build strategy rather than S2I. Sorry for that. I will keep on looking at this issue, free time given.

**Comment by goern** [comment]
I will no longer work on the s2i approach...
