### ISSUE TITLE
ERROR while creating new-app mattermost

### ISSUE THREAD

**Issue by cbeldacap** [goern/mattermost-openshift#29]
I've followed the README file in order to deploy mattermost in my cluster, but I'm always getting stuck while executing the step of `oc new-app mattermost --labels=app=mattermost`.

The error is always the same as well: 
```
error: Errors occurred while determining argument types:

mattermost as a local directory pointing to a Git repository: stat mattermost: no such file or directory

Errors occurred during resource creation:
error: multiple images or templates matched "mattermost": 2
```

Am I missing something here? I've tried in both Windows10/8GB and CentOS/8GB

Thanks in advance,
Cristóbal

**Comment by goern** [comment]
Hi there, thanks for using...

could you try `oc new-app --template=mattermost --labels=app=mattermost` and let me know if that works?

**Comment by cbeldacap** [comment]
Hi @goern ,

Already tried but I receive the same error:
![image](https://user-images.githubusercontent.com/20857839/30858382-b7dea35c-a2bf-11e7-8907-460694b50d85.png)

**Comment by goern** [comment]
hmm, this issue is dangling, sorry for that. is it still valid?

**Comment by cbeldacap** [comment]
@goern  I did not tried again... But anyway I think we can just close. I'll come back to it later on, I could always create a new one if needed :)

**Comment by goern** [comment]
ok, thanks!
