### ISSUE TITLE
Fantastic work!

### ISSUE THREAD

**Issue by it33** [goern/mattermost-openshift#3]
Wow! I'm at OSCON and the guy sitting next to me was looking at your repo, and it looked great!

Would you be open to [sharing more about your work](http://www.mattermost.org/share-your-mattermost-projects/) so we can promote it? 

Thanks so much for sharing back to the community,

**Comment by goern** [comment]
Oh Thanks! Absolutely Open! Keep in mind that it is more like a test rather than a production ready version. Let me know how and what we could do to push it!

**Comment by it33** [comment]
Thanks @goern! Could we have your help [filling out this form](https://spinpunch.wufoo.com/forms/mattermost-integrations-and-installers/) so our commuity team and compose a Tweet about you and add you to our community site?

**Comment by goern** [comment]
done.

**Comment by it33** [comment]
Thanks! Looking forward to promoting this!
