### ISSUE TITLE
Duplicated mapping key

### ISSUE THREAD

**Issue by sapkra** [goern/mattermost-openshift#32]
> Failed to process the resource.
> duplicated mapping key at line 85, column 27:
> name: mattermost

Getting this error in the openshift YAML import (GUI).
In line 57 the name is already set.
> name: ${APPLICATION_NAME}

Same for the port.

**Comment by goern** [comment]
what resource/file do you try to process?

**Comment by sapkra** [comment]
mattermost.yaml in the root of this project

It seems that there is a wrong yaml structure in this file.

You can also paste the yaml here: https://codebeautify.org/yaml-validator

**Comment by goern** [comment]
@sapkra thanks!
