### ISSUE TITLE
Openshift Online

### ISSUE THREAD

**Issue by ghost** [goern/mattermost-openshift#5]
How could I install Mattermost at Openshift Online? Could I adapt this repo for Openshift Online instead Enterprise/Origin?
Thank you in advance.

**Comment by goern** [comment]
OpenShift 3 online does not provide the docker build strategy, this is due to security concerns. I am in the process of adopting a source to image build for mattermost please stay tuned

**Comment by Peque** [comment]
I'll keep an eye on this, as I am as well interested in deploying Mattermost with OpenShift Online. :blush:

**Comment by Peque** [comment]
@goern Any updates? :blush:

**Comment by goern** [comment]
na, this is on the post #RHSummit list :/

**Comment by Peque** [comment]
@goern Oh, ok! I'll check again in a month or so.

Have fun at the RHSummit. :smile:

**Comment by Peque** [comment]
@goern Any updates? :innocent:

**Comment by goern** [comment]
duh... this takes time.. sorry about that.

**Comment by Peque** [comment]
@goern Hehehe. Yeah, I know. Such is life! :blush:

**Comment by goern** [comment]
I have tested the approach described in the README.md on OpenShift Online Starter (v3.6.173.0.7 (online version 3.5.1.79))

It worked for me :) Its up and running at http://mattermost-mattermost.193b.starter-ca-central-1.openshiftapps.com/signup_email I will kill that in a few weeks.
