### ISSUE TITLE
cannot trigger a deployment for "mattermost" because it contains unresolved images

### ISSUE THREAD

**Issue by dhanugithub** [goern/mattermost-openshift#56]
Hello, I have OpenShift 4.2 deployment where I want to deploy and run Mattermost. After following the instructions in README.md, I am getting following error when I try to start the DeploymentConfig.

cannot trigger a deployment for "mattermost" because it contains unresolved images

The imageStream is formed. Even after waiing for 10 min (just in case of slow imagestream), it didn't work. Have any idea?

**Comment by goern** [comment]
I have never tested it on OpenShift 4.2, but it sounds like the image or the tag is not available on the registry.
